bundler_args: "--without development"
rvm:
  - 1.9.3
env:
  - "CI_ORM=mongoid"
language: ruby
matrix:
  exclude:

notifications:
  #irc: "irc.freenode.org#railsadmin"
before_script:
  - cd spec/dummy_app
  - bundle install
  - bundle exec rake opiniodev:prepare_ci_env db:create db:migrate
  - cd ../../
services:
  - mongodb